# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WatermelonVedioPlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Mantle',           '2.0.7'
  pod 'ReactiveCocoa',    '2.5'
  pod 'GVUserDefaults',   '1.0.2'
  pod 'SDWebImage',       '3.8.1'
  pod 'MBProgressHUD',    '1.0.0'
  pod 'AFNetworking',     '3.1.0'
  pod 'CocoaSecurity',    '1.2.4'
  pod 'Masonry',          '1.0.1'
  pod 'FMDB',             '2.6.2'
  pod 'YTKKeyValueStore', '0.1.2'
  pod 'MJRefresh',        '3.1.9'
  pod 'DateTools',        '1.7.0'
  pod 'UTDID', '~> 1.0.0'
  pod 'ZipArchive', '~> 1.4.0'
  pod 'JSONModel', '~> 1.7.0'
  pod 'YYText'
  pod 'SHSPhoneComponent','~> 2.15'
  pod 'DACircularProgress', '~> 2.3'
  # Pods for WatermelonVedioPlayer

  target 'WatermelonVedioPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WatermelonVedioPlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
